### ISSUE TITLE
Cite statistics

### ISSUE THREAD

**Issue by abostroem** [swcarpentry/slideshows#2]
The introducing SWC slides contain some statistics that would be useful to cite (such as 96% of scientists are mostly self taught)

**Comment by willingc** [comment]
Great suggestion @abostroem. It looks like this statistic is also on the second slide of the 'best-practices' slideshow. If you have the source for the stat, please submit a PR for that slideshow :)

**Comment by wking** [comment]
On Tue, Feb 03, 2015 at 08:41:50AM -0800, Greg Wilson wrote:

> Closed #2 via 461a3c755d74906cfccbbd4ebcf0c41dad3b01ee.

Another statistic that I've always wanted a reference for is the 10X
increase in productivity (first landed here in 985ed8c8, General
overview of lessons learned, 2014-12-25).  It's currently in a few
places:

  $ git grep 10X
  best-practices/index.html:      <h4 align="center">Good programmers are<br/>10X more productive than average</h4>
  best-practices/index.html:      <h4 align="center">Good <strike>programmers</strike> are<br/>10X more productive than average</h4>
  best-practices/index.html:      <h4 align="center">Good <em><strong>practices</strong></em> are<br/>10X more productive</h4>
  hosting-workshop/index.html:        10X isn't rare
  introducing-software-carpentry/index.html:          10X isn't rare
  lessons-learned/index.html:         10X isn't rare

and it would be nice to know where it came from.  Should I open a new
issue for that (and for any other citation-needed stats), or do we
want to track them all from this issue?

**Comment by gvwilson** [comment]
It's anecdotal - a repeated anecdote, but still unfortunately not 
substantiated by anything more than 
http://software-carpentry.org/pages/testimonials.html.

**Comment by wking** [comment]
On Tue, Feb 03, 2015 at 10:37:26AM -0800, Greg Wilson wrote:

> It's anecdotal - a repeated anecdote, but still unfortunately not
> substantiated by anything more than
> http://software-carpentry.org/pages/testimonials.html.

So link to the testimonials to make that clear?

**Comment by gvwilson** [comment]
Added in #13 - if it looks good, please merge.
