### ISSUE TITLE
Slide numbers

### ISSUE THREAD

**Issue by XonqNopp** [swcarpentry/slideshows#24]
Hi, I'm not sure if I am writing this in the right place, but I just read through some of your slides on your website and I found it annoying not to have the slide number and the total number of slides while reading. It would help some people know how much longer they need to focus before the slideshow ends. It does not need to be big, it should not catch the eye. But if someone looks for it, he should find it in a corner.

That's only my opinion, I let yourself choose if it is relevant or not.

Cheers! :)

**Comment by vahtras** [comment]
+1

I agree, it is indeed recommended practice by scholars of learning.

**Comment by rgaiacs** [comment]
Slides numbers can be add using https://github.com/imakewebthings/deck.js/blob/master/introduction/index.html#L181.

@gvwilson Can you let us know why you didn't include the numbers?

**Comment by gvwilson** [comment]
Sloth and ignorance. Happy to accept a pull request.
