### ISSUE TITLE
Display total video time

### ISSUE THREAD

**Issue by jainsley** [swcarpentry/slideshows#5]
Is it possible to display the total time of the video at the right of the progress bar?

**Comment by twitwi** [comment]
Thanks for the suggestion. It should not be too difficult to do.

I opened the issue against browsercast itself: https://github.com/twitwi/deck.browsercast.js/issues/3

Let's use the current issue as a “update the browsercast version once the feature lands in browsercast”.

**Comment by twitwi** [comment]
As per closing twitwi/deck.browsercast.js#3

The suggest change should land in the slideshows next time we update the bundled deckjs+browsercast

e.g. at: http://twitwi.github.io/deck.browsercast.js-demo/pitch/
