### ISSUE TITLE
Why only Chrome as web browser?

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/slideshows#6]
At `README.md` we have

> Visualizing presentations locally with chrome (or chromium)

I launched the web server and watched the presentations with Firefox **38.0** without problem. I want to know why we **recommended** Chrome here.

**Comment by gvwilson** [comment]
@twitwi ?

**Comment by twitwi** [comment]
I see the misunderstanding. It's written as a workaround for chrome problems, I'd even recommend firefox. We should add a sentence to say that it is fine with firefox (including using file://).

**Comment by gvwilson** [comment]
Fixed in 9b4d111
