### ISSUE TITLE
Is Introductory slideshow on the SWC home page?

### ISSUE THREAD

**Issue by willingc** [swcarpentry/slideshows#7]
The length and content of the introductory slideshow is very good. http://swcarpentry.github.io/slideshows/introducing-software-carpentry/index.html

It would be a great addition (or maybe it is already there yet not prominently displayed) to the SWC main website. The voiceover is welcoming and it would be cool to have this available to all who stop by the SWC site.

**Comment by gvwilson** [comment]
Agreed - as soon as the election is out of the way, I'd like to get this 
up.  I'm also looking for a volunteer to revise the slideshow explaining 
how to set up a workshop (and do the voiceover)... :-)

**Comment by willingc** [comment]
@gvwilson Nicely moderated call this morning.

Personally, I would leave this one as is for the website since it is short and high-level. Target audience: funders, interested decision makers at universities.

I would do a separate one for "I'm interested in bringing to my campus/workplace. What happens next?"

**Comment by gvwilson** [comment]
See #10 for "what happens next" - comments welcome.
