### ISSUE TITLE
Review the slideshow on creating a workshop website

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/slideshows#8]
@willingc can you please look at swcarpentry.github.io/slideshows/creating-website/index.html ?

**Comment by willingc** [comment]
@gvwilson I took a quick glance. A good first pass. The general concepts are fine.

A few suggestions...I would keep it a little more high level when going through directions. It is likely directions will evolve over time. I would envision more a more high level (why? how? before/after) when going through the steps of install, customize, check, publish.

For example for install step, 
- Gather key workshop event information (date, time, etc)
- Graphic(s) of the end result of the step (perhaps graphic of github and local system repo, console/editor)
- Link to Instructions for step 
- While we expect this to be a straightforward process for you, things do come up. please check these help links if needed or contact us.

I'm at outreach events all day but will try to submit a PR with some slide edits. Likely breaking it up into PRs by sections of the slideshow.

**Comment by gvwilson** [comment]
See #10.
